name: Ubuntu

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: ShellCheck
        run: make lint

  tests:
    runs-on: ubuntu-22.04
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Tests
        run: make tests
